### ISSUE TITLE
[Question] How is the cursor encoded?

### ISSUE THREAD

**Issue by cryptrr** [charlie-hadden/kysely-paginate#25]
I need to create cursors on the fly for each document from the frontend itself so that I could do infinite loading.

Let's assume I have a document in my frontend

```ts
{
  id: string,
  likesCount: Number
  //...rest of the fields
}
```

I want to create the cursor for this item from `id` and `likesCount` on the frontend itself to paginate from there.

**Comment by charlie-hadden** [comment]
@cryptrr Apologies for the delayed reply here. The default cursor encoder is here https://github.com/charlie-hadden/kysely-paginate/blob/ed37a87ad9c940596fc44e6b590d6d9ba6289b8d/src/cursor.ts#L262-L295

Depending on your exact use case, the `cursorPerRow` option may also be useful: https://github.com/charlie-hadden/kysely-paginate/blob/ed37a87ad9c940596fc44e6b590d6d9ba6289b8d/test/cursor.test.ts#L52-L59
